# Generated by Django 5.0.6 on 2024-05-10 13:52

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Eyes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
            ],
        ),
        migrations.CreateModel(
            name='CusProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('image', models.CharField(max_length=255, null=True)),
                ('pattern', models.CharField(max_length=100)),
                ('yarn', models.CharField(max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hookdapi.category')),
                ('eyes', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='hookdapi.eyes')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('email_address', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=100)),
                ('is_admin', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hookdapi.customer')),
            ],
        ),
        migrations.CreateModel(
            name='CusRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='color1_requests', to='hookdapi.color')),
                ('color2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='color2_requests', to='hookdapi.color')),
                ('cus_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hookdapi.cusproduct')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hookdapi.customer')),
                ('eyes', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hookdapi.eyes')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_name', models.CharField(max_length=25)),
                ('account_number', models.CharField(max_length=25)),
                ('expiration_date', models.DateField(default='0000-00-00')),
                ('create_date', models.DateField(default='0000-00-00')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='payment_types', to='hookdapi.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(default='0000-00-00')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hookdapi.customer')),
                ('payment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='hookdapi.payment')),
            ],
        ),
        migrations.CreateModel(
            name='RTSProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.IntegerField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('description', models.CharField(max_length=255)),
                ('pattern', models.CharField(max_length=255, null=True)),
                ('yarn', models.CharField(max_length=255)),
                ('image', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hookdapi.category')),
                ('eyes', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='hookdapi.eyes')),
            ],
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cusrequest', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hookdapi.cusrequest')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hookdapi.order')),
                ('rtsproduct', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hookdapi.rtsproduct')),
            ],
        ),
    ]
