# Generated by Django 5.0.6 on 2024-07-23 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hookdapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rtssold',
            name='product_type',
            field=models.CharField(default='rtsproduct', editable=False, max_length=20),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(condition=models.Q(('emailed', False)), fields=('customer',), name='unique_open_order_per_customer'),
        ),
    ]
