# Generated by Django 5.0.6 on 2024-09-24 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hookdapi', '0002_rtssold_product_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Weight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ply', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MasterYarn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('color_name', models.CharField(max_length=100)),
                ('base_color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hookdapi.color')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hookdapi.company')),
                ('weight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hookdapi.weight')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerYarn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('color_name', models.CharField(max_length=100)),
                ('amount', models.PositiveIntegerField(default=0)),
                ('is_custom', models.BooleanField(default=False)),
                ('base_color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hookdapi.color')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hookdapi.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hookdapi.customer')),
                ('master_yarn', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hookdapi.masteryarn')),
                ('weight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hookdapi.weight')),
            ],
        ),
    ]
