# Generated by Django 5.0.6 on 2024-09-25 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hookdapi', '0003_company_weight_masteryarn_customeryarn'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customeryarn',
            old_name='user',
            new_name='customer',
        ),
    ]
